### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by jaybrawdley** [esx-framework/esx_hud#66]
it's a joke... dowload 1.5 version manifest it's 1.4 ... no comment man

**Comment by TheFantomas** [comment]
> it's a joke... dowload 1.5 version manifest it's 1.4 ... no comment man

Hello,

Thanks for reporting the problem in the old version... Version 1.10.1 is currently running. This means that this problem was fixed a long time ago. I don't know why you would download an old version and be surprised that there is an error in it. Absolutely illogical behavior from my point of view.

Thank you for your time, but this bug will not be fixed in the old version.

It's all for me...

**Best regards**
ESX Director @TheFantomas

**Comment by TheFantomas** [comment]
Sorry for the previous comment. I did not notice that it is esx_hud and not esx_core. This bug will be fixed soon.

**Comment by TheFantomas** [comment]
We will inform you how soon this will be fixed. Thanks for reporting the problem <3

**Comment by Gellipapa** [comment]
Hi! @jaybrawdley The bug has been fixed, downloaded a new release and it works. (The bug was due to automatic formatting, we rewrite the version automatically, that's why it took longer to fix) Thank you for your understanding.
